### PR TITLE
TextBox: Added set_val method for convenient scripted setting and updating.

### PR DESCRIPTION
**Pull request by smithsp**
@QuadmasterXLII 
Thanks for adding the TextBox as a Pull Request to matplotlib (https://github.com/matplotlib/matplotlib/pull/5375).  I took what you added, and added a `set_val` method.  Let me know if I need to change anything for you to accept this into your branch and thus to go into https://github.com/matplotlib/matplotlib/pull/5375.
@smithsp

### CODE REVIEW

**Comment by smithsp** [comment]
@tacaswell Can you tell why the travis build would have failed for this branch/pull request, but not for matplotlib#5375?

**Comment by tacaswell** [comment]
There may be fixes on the master branch which are not included on this branch.  I can not tell much else with out digging deeper.

**Comment by smithsp** [comment]
@tacaswell Thanks for taking a look.

**Comment by smithsp** [comment]
I am closing this because it got merged into the main matplotlib repo through a different pull request.

**Pull request closed without merging**
